eto:
  username: username
  password: password

click2mail:
  username: username
  password: password

db:
  driver: '/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.2'
  server: dbserver
  database: dbname
  username: username
  password: password

mailchimp:
  username: username
  key: key
